version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    open-pull-requests-limit: 3
